#!/usr/bin/env python3
"""scripts/dialect/board-*.sabra -> server/lib/board_embed.ml via a dune
rule.  The .sabra files are the SOURCE OF TRUTH (borg/board.borg); the
server never reads them at runtime, and this generated module is the
only copy in between.  Usage: embed_board.py <workspace_root> (module
on stdout)."""
import sys

PROGS = ["board-add", "board-view", "board-flip", "board-del"]


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    root = sys.argv[1]
    out = [
        "(* GENERATED by tools/stdprobe/embed_board.py - do not edit. *)",
        "(* Sources: scripts/dialect/board-*.sabra (borg/board.borg). *)",
        "let programs = [",
    ]
    for name in PROGS:
        with open(f"{root}/scripts/dialect/{name}.sabra") as f:
            src = f.read().strip()
        out.append(f'  ("{name}", "{esc(src)}");')
    out.append("]")
    print("\n".join(out))


main()
