(* freeze the sabra stdlib v1 vocabulary: compile the whole dictionary
   in order (def-time cross-references inline, exactly as REPL def
   rounds do) and emit

     stdlib/v1/core.defs  - def-commands, one per record, blank-line
                            separated; file order = compile order.
                            The file IS a replayable REPL transcript.
     stdlib/v1/manifest   - <name> <ternary size> <program hash>

   Both are GENERATED artifacts (source of truth: gen_defs.py);
   regenerate via this tool, never edit by hand.  Scripts/verify-8
   recomputes the manifest from the live store and diffs. *)

let compile ~dictionary src =
  Tuna_compiler.Bracket.compile_source ~fuel:100000000 ~size_cap:100000000
    ~deadline:Float.infinity ~dictionary src

let () =
  let dictionary = ref [] in
  let manifest = Buffer.create 8192 in
  let core = Buffer.create 65536 in
  Buffer.add_string core
    "# sabra stdlib v1 - GENERATED by tools/stdprobe/freeze.ml from\n\
     # tools/stdprobe/gen_defs.py. Replayable REPL transcript:\n\
     # def-commands, one per record, blank-line separated;\n\
     # file order = compile order (L0 pins .. L3 ints + engines).\n";
  List.iter
    (fun (name, src) ->
       match compile ~dictionary:!dictionary src with
       | exception Tuna_compiler.Bracket.Compile_failed m ->
           Printf.ksprintf failwith "DEF %s: %s" name m
       | art ->
           let tree = art.Tuna_compiler.Bracket.tree in
           dictionary := (name, tree) :: !dictionary;
           Buffer.add_string core (Printf.sprintf "\ndef %s %s\n" name src);
           Buffer.add_string manifest
             (Printf.sprintf "%s %d %s\n" name (Tuna.Tree.size tree)
                (Tuna.Hash.hex_of_tree tree)))
    Stddefs.all;
  let n = List.length !dictionary in
  let write path buf =
    let oc = open_out path in
    Buffer.output_buffer oc buf; close_out oc
  in
  write "stdlib/v1/core.defs" core;
  write "stdlib/v1/manifest" manifest;
  Printf.printf "froze %d defs -> stdlib/v1/{core.defs,manifest}\n" n
