(* golden: emit tests/math_prim_golden.ml - the big-vector answers for
   the math-prim differential (borg/math-prims.borg acceptance 1),
   computed under the STDLIB REFERENCE and committed as a GENERATED
   artifact (regenerate here if the vocabulary changes; the vector
   results are the F6 table's independent confirmation).

     add/sub/cmp 64-bit vectors : v0 canonical engine (~minutes-scale)
     int-mul 8-bit vector       : v1 sharing (v0 mul is F6-infeasible)

   Vectors carry (sign, LSB-first bit string) operands so the test
   rebuilds trees from small literals. *)

let compile ~dictionary src =
  Tuna_compiler.Bracket.compile_source ~fuel:100000000 ~size_cap:1000000000
    ~deadline:Float.infinity ~dictionary src

let int_tree sign bits =
  let rec go i =
    if i = String.length bits then Tuna.Tree.Leaf
    else
      Tuna.Tree.Fork
        ( (if bits.[i] = '1' then Tuna.Tree.Stem Tuna.Tree.Leaf else Tuna.Tree.Leaf)
        , go (i + 1) )
  in
  Tuna.Tree.Fork ((if sign = 1 then Tuna.Tree.Stem Tuna.Tree.Leaf else Tuna.Tree.Leaf), go 0)

let () =
  let dictionary =
    List.fold_left
      (fun acc (name, src) ->
        let art = compile ~dictionary:acc src in
        (name, art.Tuna_compiler.Bracket.tree) :: acc)
      [] Stddefs.all
  in
  let buf_add = Buffer.create 4096
  and buf_sub = Buffer.create 4096
  and buf_cmp = Buffer.create 1024
  and buf_mul = Buffer.create 1024 in
  let steps = Buffer.create 512 in
  let run mode buf def sa asb sb bsb =
    let a = int_tree sa asb and b = int_tree sb bsb in
    let art =
      compile ~dictionary
        ("(lambda (w) (" ^ def ^ " (first w) (second w)))")
    in
    match
      Tuna_interp.Eval.eval ~mode ~fuel:1000000000 ~size_cap:1000000000
        ~program:art.Tuna_compiler.Bracket.tree [ Tuna.Tree.Fork (a, b) ]
    with
    | Tuna_interp.Eval.Normal (t, n) ->
        Buffer.add_string buf
          (Printf.sprintf "  ((%d, %S), (%d, %S), %S);\n" sa asb sb bsb
             (Tuna.Canon.encode t));
        Buffer.add_string steps
          (Printf.sprintf "(* %s (%d,%s[])-(%d,%s[]): %d %s steps *)\n" def sa
             (string_of_int (String.length asb)) sb
             (string_of_int (String.length bsb)) n
             (if mode = Tuna_interp.Eval.Sharing then "v1" else "v0"))
    | _ -> failwith (def ^ " reference anomaly")
  in
  let ones n = String.make n '1' in
  let two_to_63 = String.make 63 '0' ^ "1" in
  run Tuna_interp.Eval.Canonical buf_add "int-add" 0 (ones 64) 0 (ones 64);
  run Tuna_interp.Eval.Canonical buf_add "int-add" 0 two_to_63 0 (ones 64);
  run Tuna_interp.Eval.Canonical buf_add "int-add" 1 (ones 64) 0 (ones 64);
  run Tuna_interp.Eval.Canonical buf_sub "int-sub" 0 (ones 64) 0 two_to_63;
  run Tuna_interp.Eval.Canonical buf_sub "int-sub" 1 (ones 64) 1 two_to_63;
  run Tuna_interp.Eval.Canonical buf_cmp "int-cmp" 1 (ones 64) 0 (ones 64);
  run Tuna_interp.Eval.Canonical buf_cmp "int-cmp" 0 two_to_63 0 (ones 64);
  run Tuna_interp.Eval.Canonical buf_cmp "int-cmp" 1 two_to_63 1 (ones 64);
  run Tuna_interp.Eval.Sharing buf_mul "int-mul" 0 (ones 8) 0 (ones 8);
  run Tuna_interp.Eval.Sharing buf_mul "int-mul" 1 "10101010" 0 "11001100";
  let out = open_out "tests/math_prim_golden.ml" in
  let dump name buf =
    Printf.fprintf out "let %s = [\n%s]\n\n" name (Buffer.contents buf)
  in
  output_string out
    "(* GENERATED by tools/stdprobe/golden.exe - do not edit.\n   \
     Pinned under the seeded sabra stdlib reference (see module header);\n   \
     reference step counts, one per vector:\n";
  Buffer.output_buffer out steps;
  output_string out "*)\n\ntype bits = int * string\n\n";
  dump "v_add" buf_add;
  dump "v_sub" buf_sub;
  dump "v_cmp" buf_cmp;
  dump "v_mul" buf_mul;
  close_out out;
  Buffer.output_buffer stdout steps
